### ISSUE TITLE
Demo is not working due Cannot GET /apps/demo/landing.html

### ISSUE THREAD

**Issue by rgaiacs** [camicroscope/camicroscope.github.io#2]
**To Reproduce**

1. Visit https://camicroscope.github.io/
2. Search for `Try the demo`
3. Click in the "demo" link

**Expected behavior**

Demo of caMicroscope.

**Desktop (please complete the following information):**
 - OS: GNU/Linux
 - Browser Chrome
 - Version 84

**Comment by birm** [comment]
Thanks for the report. I'm not surprised that this broke, for now, try https://wolf.cci.emory.edu//camic_org/apps/landing/landing.html

**Comment by birm** [comment]
Fixed in 3bae52173eb08ba0
