### ISSUE TITLE
Add hover effect to the community guide button.

### ISSUE THREAD

**Issue by Arpitkandwal** [camicroscope/camicroscope.github.io#20]
**Is your feature request related to a problem? Please describe.**
If you want to give your page a little twist, putting CSS button hover effects is ideal. It will help improve your visitors' dwell time. 

**Describe the solution you'd like**
I would like to add a hover effect on the community guide button, when hovering it changes color and button size increases.

**Additional context**
Before: 
![Screenshot (4)](https://user-images.githubusercontent.com/105699410/222949322-9c112e4d-7d96-4c55-87dc-24a0da5488c1.png)

After: (Before hovering):
![Screenshot (5)](https://user-images.githubusercontent.com/105699410/222949347-cd067a11-4738-40ed-92a4-30f88ef1d6a5.png)

(After hovering): The color changed and size increased.

![Screenshot (6)](https://user-images.githubusercontent.com/105699410/222949356-4fede4b1-c606-4fff-a436-6a261dda096e.png)

**Comment by Aditya-Chaurasia11** [comment]
i would like to work on this issue, please assign this to me.

**Comment by Arpitkandwal** [comment]
> i would like to work on this issue, please assign this to me.

i have already raised a pr against this
