### ISSUE TITLE
Add a favicon to the website

### ISSUE THREAD

**Issue by sohamsshah** [camicroscope/camicroscope.github.io#3]
**Is your feature request related to a problem? Please describe.**
The website doesn't have a favicon.

**Describe the solution you'd like**
Can add it to the website codebase.

**Additional context**
I suppose there can be multiple changes implemented in the website apart from this. If it is one of the priority/can be useful, then I would surely work on this. Create issues, get approved and then submit a PR to publish.

Thanks.

**Comment by birm** [comment]
Again, I'm not sure that this is a priority, but it should be a reasonably-easy fix. We have https://github.com/camicroscope/caMicroscope/blob/master/favicon.ico, but if you propose a different icon, that's ok too.

**Comment by sohamsshah** [comment]
Yes, that follows. I am fixing the favicon and linking a PR. Working on the UI redesign (currently of this website) and would revert back sooner. Also closely looking into the caMicroscope project and related issues on the repo (was trying with the Dev env setup).

How does it sound?
